version: '3'

services:
  neo4j:
    image: neo4j
    container_name: neo4j-container
    environment:
      NEO4J_AUTH: neo4j/supersecret
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app-network

  app:
    depends_on: 
      - neo4j
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    environment:
      NEO4J_URI: "bolt://neo4j:7687"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
